<html>
<head>
<title>FSCS Protection Checker Data Terms and Conditions</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Lato:400,700'>
<style type="text/css">
	body {
		font:62.5% 'lato', Arial, Helvetica, sans-serif;
		color:#683186;
	}
	h2 {
		font-size: 2.4em;
		margin: 0 0 30px;
		line-height:1.4;
	}

	p,
	li {
		font-size:1.6em;
		line-height:1.4;	
	}

</style>
</head>
<body>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<h2>FSCS Protection Checker Data Terms and Conditions</h2>
<p>This information is based on PRA data as at 26th November 2013. For the latest information about banks, building societies and credit unions authorised by the PRA and Financial Conduct Authority (FCA), check the position on the <a href="http://www.fsa.gov.uk/register/firmSearchForm.do" target="_blank">Financial Services Register</a>. For information about shared authorisations for bank and building society brands visit the <a href="http://www.fca.org.uk/consumers/complaints-and-compensation/how-to-claim-compensation/banking-and-saving/banking-and-savings-brands" target="_blank">FCA website</a>.</p>
<p>Alternatively check directly with your bank, building society or credit union or <a href="#" id="contact">contact the FSCS</a>.</p>
<p>Please note that FSCS protection applies to individuals and small businesses.</p>
<p>FSCS is not responsible for and has no control over the accuracy of the underlying data and so cannot guarantee and makes no representation to you or any other person in respect of that accuracy or the accuracy of any such result. FSCS assumes no responsibility or duty of care to you or any other person in respect of that accuracy or any reliance which you may choose to place on the result generated by the website.</p>
<p><a href="http://www.fscs.org.uk/terms-and-conditions/" target="_blank">For full terms and conditions, click here.</a></p>
</body>
</html>